### ISSUE TITLE
Rethink naming of xar

### ISSUE THREAD

**Issue by probonopd** [facebookincubator/xar#11]
According to https://en.wikipedia.org/wiki/Xar_(archiver), another high-profile archive format has been using this name since at least 10 years:

> XAR (short for eXtensible ARchive format) is an open source file archiver and the archiver’s file format. It was created within the OpenDarwin project and is used in Mac OS X 10.5 for software installation routines, as well as browser extensions in Safari 5.0. Xar replaced the use of gzipped pax files.
> 
> One development branch of RPM, RPM5, uses xar.

In order to avoid unnecessary confusion, it may be worth considering a different name for this project.

**Comment by chipturner** [comment]
The prior XAR isn't really "high profile" -- it seems pretty dead (6 years since it made a release, 4 years since it has had a commit).

**Comment by xtf0** [comment]
Yeah, but if another archiver like 7Zip, which supports Xar-Archive [0], what it will be?
I came to XAR because of search for SquashFS for python, with compabilty for archiver tools and stumbled upon this.

[0] https://7-zip.org/ features -> formats -> unpacking only -> xar
