### ISSUE TITLE
I can't run bdist_xar or make_xar

### ISSUE THREAD

**Issue by loki-ikol** [facebookincubator/xar#20]
I can execute any command, I am receiving

```
from wheel import install, paths, pep425tags, pkginfo

ImportError: cannot import name 'install'
```

I tried to reproduce it, I also tried to run it inside a docker container but same error, any ideas?

**Comment by terrelln** [comment]
Thanks for the report @loki-ikol!

It looks like wheel removed the API that they provided. For a short term fix you can install an older version of wheel. It looks like `wheel<=0.31.1` will work.

I'll remove the dependency on wheel in the next week.

**Comment by terrelln** [comment]
I've added the constraint `wheel<=0.31.1` to the master branch. I'll cut a new release shortly.
