### ISSUE TITLE
make_xar fails to find __main__

### ISSUE THREAD

**Issue by apt-itude** [facebookincubator/xar#21]
# Problem
Running `make_xar` on a directory containing a `__main__.py` file (which the documentation suggests is a supported behavior) fails with the following stack trace:
```
$ make_xar --python runfiles/ --python-interpreter python3.6 --output testxar
Traceback (most recent call last):
  File "/Users/athompson/.pyenv/versions/xar/bin/make_xar", line 11, in <module>
    sys.exit(main())
  File "/Users/athompson/.pyenv/versions/3.7.0/envs/xar/lib/python3.7/site-packages/xar/make_xar.py", line 123, in main
    entry_point = entry_point or xar_util.get_python_main(opts.python)
AttributeError: module 'xar.xar_util' has no attribute 'get_python_main'
```
Looking at the code, it actually does look like this function is not implemented.

# Environment
* OS: macOS Mojave (10.14) 
* `xar` version: 18.7.12
* Python version: 3.7.0

**Comment by terrelln** [comment]
This should be fixed in the master branch. I'll release a new version soon.
