### ISSUE TITLE
Please clarify requirements in README

### ISSUE THREAD

**Issue by mig4** [facebookincubator/xar#25]
XAR is currently described as producing "self-contained executable files", unfortunately that's not exactly the case as it requires `xarexec_fuse` and `squashfuse` installed on the target system. There's nothing wrong with that but it makes it less suitable for use to distribute produced artifacts to third-parties so I think this should be highlighted in the intro.

Also, could you please clarify/expand the [Requirements](https://github.com/facebookincubator/xar#requirements) section in the README to distinguish between requirements for development/building of XAR archives and runtime requirements?

**Comment by cooperlees** [comment]
Hi @mig4 

Thanks and I get your point, but do not 100% agree. The goal of XAR (and PEX etc.) is to bundle all the Python + C/C++ code into a single executable and it achieves that. That said, I will take a look at the README and add some words to address your concerns. We do not state anywhere that we do not have any dependencies. We would also need to bundle the Python interpreter (and people have) into XARs to be 100% academically correct as well, and hope one day for this to be contributed.
