### ISSUE TITLE
Support for other Python 3.x versions

### ISSUE THREAD

**Issue by timabbott** [facebookincubator/xar#26]
I noticed that this package only officially supports Python 2.6 and 3.6; is there a reason you'd expect it to not work on with 3.5/3.7, or have you just not tested it for those?

**Comment by cooperlees** [comment]
We've only tested with:
- 2.7
*(Never 2.6)*
- 3.5
- 3.6

`README.md` sepecifies Python >= 2.7.11 & >= 3.5.

I'd expect it to work with 3.7, unless a dep or our code has a bug. Have cut https://github.com/facebookincubator/xar/issues/28 to get CircleCI testing with 3.7.

**Comment by cooperlees** [comment]
Felt I answered this.

**Comment by timabbott** [comment]
Great, thanks!
