### ISSUE TITLE
UserWarning when install

### ISSUE THREAD

**Issue by Hanaasagi** [facebookincubator/xar#33]
Run `python setup.py install` 

```
/usr/lib64/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'test_require'
  warnings.warn(msg)     
```

https://github.com/facebookincubator/xar/blob/38398a19651dc1d8b6b1e0206c6a6fff7a2aae08/setup.py#L44

It should be `tests_require` instead of `test_requires`.

Ref: https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=tests_require#new-and-changed-setup-keywords

**Comment by cooperlees** [comment]
Thanks for finding this. PR welcome or we will try get to it this week.

**Comment by Hanaasagi** [comment]
Done.
