### ISSUE TITLE
XAR for CentOs and Windows

### ISSUE THREAD

**Issue by Shashank0719** [facebookincubator/xar#35]
Hi ,

It's a great one. Thanks for making one. I am seeking one help. I want to make XAR for windows and CentOs also. Could you please help me by letting me know how to do the same.

Thanks  & regards,
Shashank Singh

**Comment by cooperlees** [comment]
We do not currently support Windows. There is no roadmap for adding support either, unfortunately.

We would LOVE this support tho. We need a way to mount SquashFS on windows, then we can start to look at support.

XAR should be able to function WSL tho, which could be an elegant hack.

**Comment by Shashank0719** [comment]
Hey ,

Thanks a lot fir quick reply. Can you tell me about that hack. And explain
lil bit more. And Whether XAR will work with CentOS also?

Regards,
Shashank Singh

**Comment by thedrow** [comment]
I think XARs should work on any Linux distribution where you can compile the dependencies.

**Comment by cooperlees** [comment]
Facebook is *mostly* CentOS internally, so XAR is in fact most tested on CentOS. So it definately works :).

**Comment by terrelln** [comment]
We don't support Windows for XARs. We *may* accept a PR that adds support, but it's a pretty inactive project, so getting review time would be hard. If you need windows support, I'd suggest forking.
