### ISSUE TITLE
Alpine support

### ISSUE THREAD

**Issue by thedrow** [facebookincubator/xar#36]
Do we support Alpine?
If not, I believe we should as it is the target to many containers.

**Comment by cooperlees** [comment]
Hello. We haven't tested or documented Alpine, but I can not see why it wouldn't. I would just expect you'd need to compile a lot of XAR's dependencies from source. To see what it needs, please look at the README.md [here](https://github.com/facebookincubator/xar#requirements).

**Comment by thedrow** [comment]
I'll try it.
But why close the issue? Is it something we don't want to officially support?

**Comment by cooperlees** [comment]
I closed the issue as it was a very generic question. I answered it, and I expect XAR to work on Alpine Linux. The README.me does state it should work on basically all variants of Linux with the dependencies installed.

If you hit an actual issue or bug with XAR itself, please create an issue.
