### ISSUE TITLE
Provide binaries for xarexec_fuse

### ISSUE THREAD

**Issue by thedrow** [facebookincubator/xar#38]
We should not be building this executable from source.
Instead, we should be able to simply download it.

**Comment by cooperlees** [comment]
Hi, thanks for the suggestion. We are not a binary building company. Please open an issue to add it to your distribution or package manager of choice if you do not wish to not build. We did our documentation this way as it covered the most target install platforms.

**Comment by thedrow** [comment]
If you want your project to spread you probably need to do it anyway.
In any case, this can easily be automated through CI.
Why not do it?
