### ISSUE TITLE
bdist_xar in a pipenv

### ISSUE THREAD

**Issue by nathantsoi** [facebookincubator/xar#7]
trying out the xar distutils extension, but having trouble getting it running w/in pipenv

basically don't see the bdist_xar extension when running distutils:

```
pipenv run python setup.py --help-commands
Standard commands:
  build            build everything needed to install
  build_py         "build" pure Python modules (copy to build directory)
  build_ext        build C/C++ extensions (compile/link to build directory)
  build_clib       build C/C++ libraries used by Python extensions
  build_scripts    "build" scripts (copy and fixup #! line)
  clean            clean up temporary files from 'build' command
  install          install everything from build directory
  install_lib      install all Python modules (extensions and pure Python)
  install_headers  install C/C++ header files
  install_scripts  install scripts (Python or otherwise)
  install_data     install data files
  sdist            create a source distribution (tarball, zip file, etc.)
  register         register the distribution with the Python package index
  bdist            create a built (binary) distribution
  bdist_dumb       create a "dumb" built distribution
  bdist_rpm        create an RPM distribution
  bdist_wininst    create an executable installer for MS Windows
  check            perform some checks on the package
  upload           upload binary package to PyPI

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
```

on mac and have installed xar via brew per the instructions: https://code.fb.com/data-infrastructure/xars-a-more-efficient-open-source-system-for-self-contained-executables/

in the pipenv i install the extensions by cloning xar, cding into the directory and:

```
pipenv run pip install .
```

still dont get the extension, but if I import it in my setup.py, it works fine, until the build directory is cleaned:

```
from xar.commands.bdist_xar import bdist_xar
setup(
...
    cmdclass={'bdist_xar': bdist_xar},
...
)
```

then:

```
› per python setup.py bdist_xar
running bdist_xar
running bdist_wheel
running build
running build_py
creating build
creating build/lib
copying collector.py -> build/lib
removing 'build/bdist.macosx-10.12-x86_64/xar' (and everything under it)
error: [Errno 2] No such file or directory: 'build/bdist.macosx-10.12-x86_64/xar'
```

any direction is much appreciated

**Comment by terrelln** [comment]
I'm able to get the extension using these commands:

```
git clone https://github.com/ambv/black && cd black
pyenv install xar
pyenv run python setup.py bdist_xar
./dist/black.xar --help
```

Can you tell me what versions of XAR's dependencies you are using so I can try to reproduce the error you are seeing? I haven't ben able to yet.

**Comment by nathantsoi** [comment]
I actually didn't try it w/o pipenv. I did use pyenv to install the underlying python 3.7 though

**Comment by terrelln** [comment]
@nathantsoi thats my fault, I ran `pipenv` not `pyenv`.

What version of XAR's dependencies are you using? Most importantly setuptools & wheel.

**Comment by nathantsoi** [comment]
hum... running your example above worked fine. inspired by success, i ran `pipenv --rm` and removed my `~/.pyenv`  then `pipenv install xar`'d in my project after re-installing python and the pipenv and all is well! not sure what was broken, but thanks for the help!

for reference:
```
xar==18.7.12
  - pip [required: >=10.0.1, installed: 10.0.1]
  - setuptools [required: >=34.1, installed: 40.0.0]
  - wheel [required: Any, installed: 0.31.1]
```

**Comment by nathantsoi** [comment]
fwiw, i found that i usually have to `pipenv install xar` then `pipenv --rm` then `pipenv install` before I can run `...setup.py bdist_xar`. it's unclear to me why this is necessary

if i do not `--rm` my pipenv first, I get:
```
› pipenv run python setup.py bdist_xar
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_xar'
```
which is maybe a problem with pipenv?

**Comment by terrelln** [comment]
I haven't been able to reproduce that problem. I ran these commands and everything worked (except for the issue in #13):

```
git clone https://github.com/nathantsoi/xar_packaging_test
cd xar_packaging_test
pipenv install xar
pipenv run setup.py bdist_xar
```

**Comment by nathantsoi** [comment]
weird, ok. thx for checking!

**Comment by nathantsoi** [comment]
actually, thinking about this, i've never had the problem if the Pipfile file contains the `xar` dependency when running `pipenv install` for the first time

i wonder if it is only broken when a virtualenv has already been created by `pipenv install` without having specified `xar`, which is then installed later. maybe setuptools / distutils (not sure which it is) doesn't know about the `xar` extensions?
